// Code generated by protoc-gen-go.
// source: github.com/micro/go-grpc/examples/greeter/server/proto/hello/hello.proto
// DO NOT EDIT!

/*
Package go_micro_srv_greeter is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/go-grpc/examples/greeter/server/proto/hello/hello.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.greeter.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.greeter.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Say service

type SayClient interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type sayClient struct {
	c           client.Client
	serviceName string
}

func NewSayClient(serviceName string, c client.Client) SayClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.greeter"
	}
	return &sayClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *sayClient) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Say.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Say service

type SayHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterSayHandler(s server.Server, hdlr SayHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Say{hdlr}, opts...))
}

type Say struct {
	SayHandler
}

func (h *Say) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.SayHandler.Hello(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/micro/go-grpc/examples/greeter/server/proto/hello/hello.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x8e, 0xcf, 0x0a, 0xc2, 0x30,
	0x0c, 0x87, 0x1d, 0xf3, 0x6f, 0x4f, 0x52, 0x3c, 0x88, 0x38, 0x91, 0x9d, 0xbc, 0xd8, 0x82, 0xbe,
	0xc4, 0x6e, 0xc2, 0x7c, 0x82, 0x6d, 0x84, 0x6e, 0xb0, 0xae, 0x35, 0xe9, 0x86, 0xbe, 0xbd, 0xae,
	0xf6, 0xa8, 0x97, 0xe4, 0x47, 0x3e, 0x92, 0x2f, 0x2c, 0x53, 0x8d, 0xab, 0xfb, 0x52, 0x54, 0x46,
	0x4b, 0xdd, 0x54, 0x68, 0xa4, 0x32, 0x67, 0x85, 0xb6, 0x92, 0xf0, 0x2c, 0xb4, 0x6d, 0x81, 0xa4,
	0x42, 0x00, 0x07, 0x28, 0x09, 0x70, 0xf8, 0x34, 0x8b, 0xc6, 0x19, 0x59, 0x43, 0xdb, 0x86, 0x2a,
	0xfc, 0x84, 0x6f, 0x94, 0x11, 0xfe, 0x82, 0x20, 0x1c, 0x44, 0x58, 0x4a, 0x13, 0xb6, 0xc8, 0xe1,
	0xd1, 0x03, 0x39, 0xce, 0xd9, 0xb4, 0x2b, 0x34, 0x6c, 0xa3, 0x63, 0x74, 0x5a, 0xe5, 0x3e, 0xa7,
	0x7b, 0xb6, 0xcc, 0x81, 0xac, 0xe9, 0x08, 0xf8, 0x9a, 0xc5, 0x9a, 0x54, 0xc0, 0x63, 0xbc, 0xdc,
	0x58, 0x7c, 0x2f, 0x5e, 0x3c, 0x63, 0xb3, 0x6c, 0x14, 0xf1, 0x44, 0xfc, 0x72, 0x88, 0x20, 0xd8,
	0x1d, 0xfe, 0xe1, 0xaf, 0x20, 0x9d, 0x94, 0x73, 0xff, 0xea, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0x68, 0x96, 0xe9, 0xf6, 0x00, 0x00, 0x00,
}
